import type { EmotionConfig } from '@/types/garden';
import type { EmotionKey } from '@/types/mood';

export const EMOTIONS: Record<EmotionKey, EmotionConfig> = {
  happy: {
    key: 'happy',
    label: '开心',
    emoji: '😊',
    color: '#C8994B',
    bgColor: '#FBF3E2',
    sceneColor: '#C8994B',
    plants: ['sunflower'],
    effects: ['gold-spark', 'butterfly'],
    timeOfDay: 'day',
  },
  calm: {
    key: 'calm',
    label: '平静',
    emoji: '🍃',
    color: '#8FA07A',
    bgColor: '#EEF2E8',
    sceneColor: '#8FA07A',
    plants: ['white-flower', 'grass'],
    effects: ['breeze'],
    timeOfDay: 'day',
    recommendedAmbient: 'stream',
  },
  excited: {
    key: 'excited',
    label: '兴奋',
    emoji: '✨',
    color: '#C97E73',
    bgColor: '#F9EDE9',
    sceneColor: '#C97E73',
    plants: ['firework-flower'],
    effects: ['rainbow', 'sparkle'],
    timeOfDay: 'dusk',
  },
  anxious: {
    key: 'anxious',
    label: '焦虑',
    emoji: '🌧️',
    color: '#8B96A8',
    bgColor: '#EBEDF1',
    sceneColor: '#8B96A8',
    plants: ['blue-thorn'],
    effects: ['rain', 'fog'],
    timeOfDay: 'overcast',
    recommendedAmbient: 'rain',
  },
  confused: {
    key: 'confused',
    label: '迷茫',
    emoji: '🌫️',
    color: '#A898B0',
    bgColor: '#F0ECF3',
    sceneColor: '#A898B0',
    plants: ['purple-flower-sea'],
    effects: ['floating-cloud'],
    timeOfDay: 'dusk',
    recommendedAmbient: 'ocean',
  },
  sad: {
    key: 'sad',
    label: '难过',
    emoji: '🌙',
    color: '#8B8B9B',
    bgColor: '#ECECF0',
    sceneColor: '#8B8B9B',
    plants: ['moonlight-flower'],
    effects: ['firefly'],
    timeOfDay: 'night',
    recommendedAmbient: 'ocean',
  },
  angry: {
    key: 'angry',
    label: '愤怒',
    emoji: '⚡',
    color: '#BF7B67',
    bgColor: '#F6EBE6',
    sceneColor: '#BF7B67',
    plants: ['red-spider-lily'],
    effects: ['flame'],
    timeOfDay: 'dusk',
    recommendedAmbient: 'stream',
  },
  lonely: {
    key: 'lonely',
    label: '孤独',
    emoji: '❄️',
    color: '#9DA9B0',
    bgColor: '#EDF0F1',
    sceneColor: '#9DA9B0',
    plants: ['snow-tree'],
    effects: ['cold-glow', 'snow'],
    timeOfDay: 'night',
    recommendedAmbient: 'forest',
  },
};

export const EMOTION_LIST: EmotionConfig[] = [
  EMOTIONS.happy,
  EMOTIONS.calm,
  EMOTIONS.excited,
  EMOTIONS.anxious,
  EMOTIONS.confused,
  EMOTIONS.sad,
  EMOTIONS.angry,
  EMOTIONS.lonely,
];

export function getEmotionConfig(key: EmotionKey): EmotionConfig {
  return EMOTIONS[key];
}
